# Generated by Django 2.0.4 on 2018-04-11 17:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artNum', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=20)),
                ('totBoxes', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Orphan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxNum', models.CharField(max_length=1, verbose_name='Box Number')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orphans.Article')),
            ],
        ),
        migrations.CreateModel(
            name='OrphanInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across the entire store', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Available'), ('s', 'Spare Parts'), ('o', 'Open/Damaged')], default='a', help_text='Orphan Box Status', max_length=1)),
                ('orphan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orphans.Orphan')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
