# Generated by Django 2.0.4 on 2018-04-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphans', '0002_orphaninstance_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orphaninstance',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='article',
            name='totBoxes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='boxNum',
            field=models.IntegerField(verbose_name='Box Number'),
        ),
    ]
